services:
  nds-build:
    image: devkitpro/devkitarm:latest
    volumes:
      - .:/nds
    working_dir: /nds
    user: "${UID}:${GID}"
    command: make
    environment:
      - DEVKITARM=/opt/devkitpro/devkitARM
      - DEVKITPRO=/opt/devkitpro
    tty: true
    stdin_open: true

  nds-dev:
    image: devkitpro/devkitarm:latest
    volumes:
      - .:/nds
    working_dir: /nds
    user: "${UID}:${GID}"
    command: /bin/bash
    environment:
      - DEVKITARM=/opt/devkitpro/devkitARM
      - DEVKITPRO=/opt/devkitpro
    tty: true
    stdin_open: true
